In [1]:
import numpy as np

In [2]:
grid = [[7, 8, 0, 4, 0, 0, 1, 2, 0],
        [6, 0, 0, 0, 7, 5, 0, 0, 9],
        [0, 0, 0, 6, 0, 1, 0, 7, 8],
        [0, 0, 7, 0, 4, 0, 2, 6, 0],
        [0, 0, 1, 0, 5, 0, 9, 3, 0],
        [9, 0, 4, 0, 6, 0, 0, 0, 5],
        [0, 7, 0, 3, 0, 0, 0, 1, 2],
        [1, 2, 0, 0, 0, 7, 4, 0, 0],
        [0, 4, 9, 2, 0, 6, 0, 0, 7]]
print(np.matrix(grid))

[[7 8 0 4 0 0 1 2 0]
 [6 0 0 0 7 5 0 0 9]
 [0 0 0 6 0 1 0 7 8]
 [0 0 7 0 4 0 2 6 0]
 [0 0 1 0 5 0 9 3 0]
 [9 0 4 0 6 0 0 0 5]
 [0 7 0 3 0 0 0 1 2]
 [1 2 0 0 0 7 4 0 0]
 [0 4 9 2 0 6 0 0 7]]


In [3]:
def isSafe(row,col,num):
    global grid
    for i in range(9):
        if (grid[row][i] == num) or (grid[i][col] == num) :
            return False
    xo = (row//3) * 3
    yo = (col//3) * 3
    for i in range(3):
        for j in range(3):
            if (grid[xo+i][yo+j] == num):
                return False
    return True

In [4]:
def solve():
    global grid
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:
                for n in range(1,10):
                    if isSafe(i,j,n):
                        grid[i][j] = n
                        solve()
                        grid[i][j] = 0
                return
    print(np.matrix(grid))

In [5]:
solve()

[[7 8 5 4 3 9 1 2 6]
 [6 1 2 8 7 5 3 4 9]
 [4 9 3 6 2 1 5 7 8]
 [8 5 7 9 4 3 2 6 1]
 [2 6 1 7 5 8 9 3 4]
 [9 3 4 1 6 2 7 8 5]
 [5 7 8 3 9 4 6 1 2]
 [1 2 6 5 8 7 4 9 3]
 [3 4 9 2 1 6 8 5 7]]
